Ticket #1248 Fix RPM/Debian package and port latest changes from master
Squashed commit of the following:

commit e46fb9342b6c3b7e5d29c67fa21296048e886e2a
Author: Thawan Kooburat <kooburat@cs.wisc.edu>
Date:   Fri Aug 13 20:00:15 2010 -0500

    - Bug fix

commit 95b8cb8fb154c2a71f2580af4f40d19819a716c5
Author: Thawan Kooburat <kooburat@cs.wisc.edu>
Date:   Fri Aug 13 19:40:51 2010 -0500

    - Relocate empty folder generation

commit 13d0ef44cc705ec1524a22e4e9f824fcc1803eb4
Merge: c0a3847 ffb41a6
Author: Thawan Kooburat <kooburat@cs.wisc.edu>
Date:   Fri Aug 13 18:35:49 2010 -0500

    Merge branch 'V7_5-cpack-stage-branch' of ssh://paneer.cs.wisc.edu/scratch/kooburat/workspace-master into V7_5-cpack-stage-branch

commit ffb41a6af2669ea661faf2766213d3f7a5f253e3
Author: Thawan Kooburat <kooburat@cs.wisc.edu>
Date:   Fri Aug 13 18:33:52 2010 -0500

    - Add modified CPack modules for reference

commit c0a384740976cf37a83ebe0bf2b6fa1544ba94a6
Author: Thawan Kooburat <kooburat@cs.wisc.edu>
Date:   Fri Aug 13 18:26:09 2010 -0500

    - Add init script patch for debian

commit 8c256fb3fc7ed1e8d09a0af3f1596eb4972a34a0
Merge: 5e89b7a 6e7d522
Author: Thawan Kooburat <kooburat@cs.wisc.edu>
Date:   Fri Aug 13 16:45:01 2010 -0500

    Merge branch 'V7_5-cpack-stage-branch' of ssh://paneer.cs.wisc.edu/scratch/kooburat/workspace-master into V7_5-cpack-stage-branch

commit 5e89b7a5668b4ff387fa6496d2571f2420f4cc1c
Author: Thawan Kooburat <kooburat@cs.wisc.edu>
Date:   Fri Aug 13 16:44:24 2010 -0500

    - Add modified CPackRPM module

commit 6e7d522bc97df432d9f9f0d4ae77f40d21d440fe
Author: Thawan Kooburat <kooburat@cs.wisc.edu>
Date:   Fri Aug 13 16:41:58 2010 -0500

    - Add modified CPackDeb module

commit f3cbe8f41345a4f83692f5291c7f956f4c894efc
Author: Thawan Kooburat <kooburat@cs.wisc.edu>
Date:   Fri Aug 13 15:31:46 2010 -0500

    - Tweak Debian stuff

commit a184394cdefea9be237752f8bd6e8a0a9de97ed5
Merge: a68bdd1 a36f99e
Author: Thawan Kooburat <kooburat@cs.wisc.edu>
Date:   Fri Aug 13 15:21:08 2010 -0500

    Merge branch 'V7_5-cmake-stage-branch' of /p/condor/repository/CONDOR_SRC into V7_5-cpack-stage-branch

commit a68bdd1dd818cec5628a251589f10c546589f3cc
Author: Thawan Kooburat <kooburat@cs.wisc.edu>
Date:   Fri Aug 13 13:25:55 2010 -0500

    - Fix rpm generation error (Set INSTALL_PREFIX = "")

commit e83782f6d4c7707ae0bd473a485823bf966c9b7d
Author: Thawan Kooburat <kooburat@cs.wisc.edu>
Date:   Fri Aug 13 11:45:33 2010 -0500

    - Add stuff removed from re-organizing

commit 008d60e60a1885ee041a58158b4ae2262e65c83d
Author: Thawan Kooburat <kooburat@cs.wisc.edu>
Date:   Thu Aug 12 17:33:28 2010 -0500

    - Port package conf changes from 7.5.3

diff --git a/build/packaging/debian/postinst b/build/packaging/debian/postinst
--- a/build/packaging/debian/postinst
+++ b/build/packaging/debian/postinst
@@ -24,14 +24,12 @@ configure_condor(){
 	#Debian guarantee that this program is in PATH
 	ldconfig
 
-	#We don't want to start condor by default
-	#So that user can edit condor_config 
-
 }
 
 start_service(){
-	set +e	
-	#Start condor service
+	
+	# Stop condor service
+	# It will fail if condor is not stopped in time limit
 	if [ -x "/etc/init.d/condor" ]; then
 	  if which invoke-rc.d >/dev/null 2>&1; then
      		invoke-rc.d condor start
@@ -39,7 +37,7 @@ start_service(){
      		/etc/init.d/condor start
      	  fi
 	fi
-	set -e	
+	
 }
 
 
@@ -51,19 +49,23 @@ change_permission() {
 }
 
 case "$1" in
-    configure)
-	configure_condor
-	change_permission
-	start_service
-    ;;
+	configure)
+		configure_condor
+		change_permission
+	
+		#We don't want to start condor by default
+		#So that user can edit condor_config 
+		
+		#start_service
+	;;
 
-    abort-upgrade|abort-remove|abort-deconfigure)
-    ;;
+	abort-upgrade|abort-remove|abort-deconfigure)
+	;;
 
-    *)
-        echo "postinst called with unknown argument \`$1'" >&2
-        exit 1
-    ;;
+	*)
+		echo "postinst called with unknown argument \`$1'" >&2
+		exit 1
+	;;
 esac
 
 # dh_installdeb will replace this with shell code automatically
diff --git a/build/packaging/debian/preinst b/build/packaging/debian/preinst
--- a/build/packaging/debian/preinst
+++ b/build/packaging/debian/preinst
@@ -20,8 +20,9 @@ GECOS="Condor Daemons"
 HOME=/var/lib/condor
 
 stop_service(){
-	set +e	
-	#Stop condor service
+	
+	# Stop condor service
+	# It will fail if condor is not stopped in time limit
 	if [ -x "/etc/init.d/condor" ]; then
 	  if which invoke-rc.d >/dev/null 2>&1; then
      		invoke-rc.d condor stop
@@ -29,7 +30,7 @@ stop_service(){
      		/etc/init.d/condor stop
      	  fi
 	fi
-	set -e	
+	
 }
 
 create_user(){
@@ -53,21 +54,21 @@ create_user(){
 
 
 case "$1" in
-    install)
-        stop_service
-	create_user
-    ;;
+	install)
+		#stop_service
+		create_user
+	;;
 
-    upgrade)
-    ;;
+	upgrade)
+	;;
 
-    abort-upgrade)
-    ;;
+	abort-upgrade)
+	;;
 
-    *)
-        echo "preinst called with unknown argument \`$1'" >&2
-        exit 1
-    ;;
+	*)
+		echo "preinst called with unknown argument \`$1'" >&2
+		exit 1
+	;;
 esac
 
 # dh_installdeb will replace this with shell code automatically
diff --git a/build/packaging/debian/prerm b/build/packaging/debian/prerm
--- a/build/packaging/debian/prerm
+++ b/build/packaging/debian/prerm
@@ -18,8 +18,9 @@ set -e
 
 
 stop_service(){
-	set +e
-	#Stop condor service
+	
+	# Stop condor service
+	# It will fail if condor is not stopped in time limit
 	if [ -x "/etc/init.d/condor" ]; then
 	  if which invoke-rc.d >/dev/null 2>&1; then
      		invoke-rc.d condor stop
@@ -27,23 +28,26 @@ stop_service(){
      		/etc/init.d/condor stop
      	  fi
 	fi
-	set -e
+	
 }
 
 
 
 case "$1" in
-    remove|upgrade|deconfigure)
-	stop_service
-    ;;
+	remove)
+		stop_service
+	;;
 
-    failed-upgrade)
-    ;;
+	upgrade|deconfigure)
+	;;
 
-    *)
-        echo "prerm called with unknown argument \`$1'" >&2
-        exit 1
-    ;;
+	failed-upgrade)
+	;;
+
+	*)
+		echo "prerm called with unknown argument \`$1'" >&2
+		exit 1
+	;;
 esac
 
 # dh_installdeb will replace this with shell code automatically
diff --git a/build/packaging/rpm/condor.spec.in b/build/packaging/rpm/condor.spec.in
--- a/build/packaging/rpm/condor.spec.in
+++ b/build/packaging/rpm/condor.spec.in
@@ -91,10 +91,11 @@ getent passwd condor >/dev/null || \
   useradd -r -g condor -d %_var/lib/condor -s /sbin/nologin \
     -c "Owner of Condor Daemons" condor
 
-if [ "$1" -ge "2" ]; then
-  #Stopping condor if there is existing version
-  /sbin/service condor stop >/dev/null 2>&1 || :
-fi
+#Condor master will restart its daemon automatically if updated
+#Stopping condor if there is existing version
+#if [ "$1" -ge "2" ]; then
+#  /sbin/service condor stop >/dev/null 2>&1 || :
+#fi
 
 exit 0
 
@@ -108,20 +109,34 @@ VAR=$RPM_INSTALL_PREFIX2
 #Patch config file if relocated
 
 if [ $USR != "/usr" ] ; then
-  perl -p -i -e "s:^CONDOR_CONFIG_VAL=.*:CONDOR_CONFIG_VAL=$USR/bin/condor_config_val:" $ETC/init.d/condor 
+  #Patch parameters which are affected by /usr relocation
+  perl -p -i -e "s:^CONDOR_CONFIG_VAL=.*:CONDOR_CONFIG_VAL=$USR/bin/condor_config_val:" $ETC/sysconfig/condor 
   perl -p -i -e "s:^RELEASE_DIR(\s*)=.*:RELEASE_DIR\$1= $USR:" $ETC/condor/condor_config   
+
+  #If man folder is in the same level as bin and sbin, man can find manpages without setting the manpath
+  #Add softlink to do achieve this
+  old_path=`pwd`
+  cd $USR
+  ln -sf share/man 
+  cd $old_path
 fi
 
 if [ $VAR != "/var" ] ; then
+  #Patch parameters which are affected by /var relocation
   perl -p -i -e "s:^LOCAL_DIR(\s*)=.*:LOCAL_DIR\$1= $VAR:" $ETC/condor/condor_config   
 fi
 
 if [ $ETC != "/etc" ] ; then
-  perl -p -i -e "s:^CONDOR_CONFIG=.*:CONDOR_CONFIG=$ETC/condor/condor_config:" $ETC/init.d/condor 
-  perl -p -i -e "s:^LOCAL_CONFIG_FILE(\s*)=\s*/etc(.*):LOCAL_CONFIG_FILE\$1= $ETC\$2:" $ETC/condor/condor_config 
+  #Patch parameters which are affected by /etc relocation
+  perl -p -i -e "s:^CONDOR_CONFIG=.*:CONDOR_CONFIG=$ETC/condor/condor_config:" $ETC/sysconfig/condor
+  perl -p -i -e "s:^LOCAL_CONFIG_FILE(\s*)=\s*/etc(.*):LOCAL_CONFIG_FILE\$1= $ETC\$2:" $ETC/condor/condor_config
+  perl -p -i -e "s:^LOCAL_CONFIG_DIR(\s*)=\s*/etc(.*):LOCAL_CONFIG_DIR\$1= $ETC\$2:" $ETC/condor/condor_config
   
-  #Install init.d script
-  cp -f $ETC/init.d/condor /etc/init.d/condor  
+  #Install init script and sysconfig only if this is the first instance
+  if [ $1 = 1 ]; then
+     cp -f $ETC/init.d/condor /etc/init.d/condor  
+     cp -f $ETC/sysconfig/condor /etc/sysconfig/condor  
+  fi
 fi
 
 
@@ -139,24 +154,36 @@ exit 0
 %preun -n condor
 
 #Stop condor
-/sbin/service condor stop >/dev/null 2>&1 || :
+#/sbin/service condor stop >/dev/null 2>&1 || :
+
+#Stop and remove condor only when this is the last instance
 if [ $1 = 0 ]; then
-  
-  /sbin/chkconfig --del condor
+  #This should fail if it is unable to stop condor in timelimit
+  /sbin/service condor stop
+  if [ $? = 1 ]; then
+     echo "Abort uninstallation"
+     exit 1;
+  fi
+
+  if [ -e /etc/init.d/condor ]; then
+     /sbin/chkconfig --del condor
+  fi
   
   #Remove init.d if relocated
   ETC=$RPM_INSTALL_PREFIX0
   if [ $ETC != "/etc" ] ; then    
     rm /etc/init.d/condor
+    rm /etc/sysconfig/condor
   fi
 
 fi
 
 
 %postun -n condor
-#if [ "$1" -ge "1" ]; then
-  #Upgrading or remove but other version existed 
-  #/sbin/service condor restart >/dev/null 2>&1 || :
+# We do not need to do anything, Condor will detec binary changes and restart itself automatically
+#Upgrading or remove but other version existed 
+#if [ "$1" -ge "1" ]; then  
+#  /sbin/service condor restart >/dev/null 2>&1 || :
 #fi
 /sbin/ldconfig
 
@@ -164,6 +191,12 @@ fi
 %changelog
 * @CPACK_RPM_DATE@  <condor-users@cs.wisc.edu> - @CPACK_RPM_PACKAGE_VERSION@-@CPACK_RPM_PACKAGE_RELEASE@
 - Please see version history at http://www.cs.wisc.edu/condor/manual/v@CPACK_RPM_PACKAGE_VERSION@/8_Version_History.html
+
+* Thu Aug 12 2010  <kooburat@cs.wisc.edu> - 7.5.3
+- Add /etc/condor/config.d directory
+- Add configuration file /etc/sysconfig/condor
+- Add support for condor_drone
+- Disable auto-restart on update, let condor_master handle it  
 
 * Sun Jan 24 2010  <kooburat@cs.wisc.edu> - 7.5.0-2
 - Make RPM relocatable and support multiple version install
